//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLT.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CLTEntities : DbContext
    {
        public CLTEntities()
            : base("name=CLTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Competitions> Competitions { get; set; }
        public virtual DbSet<CompTeams> CompTeams { get; set; }
        public virtual DbSet<Fixtures> Fixtures { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Matches> Matches { get; set; }
        public virtual DbSet<MatchEvents> MatchEvents { get; set; }
        public virtual DbSet<Players> Players { get; set; }
        public virtual DbSet<PlayerSkills> PlayerSkills { get; set; }
        public virtual DbSet<PlayerTypes> PlayerTypes { get; set; }
        public virtual DbSet<TeamInducements> TeamInducements { get; set; }
        public virtual DbSet<TeamMatchData> TeamMatchData { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<TypeGroups> TypeGroups { get; set; }
        public virtual DbSet<GroupTables> GroupTables { get; set; }
    }
}
