//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixtures
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fixtures()
        {
            this.Matches = new HashSet<Matches>();
        }
    
        public int ID { get; set; }
        public int Group { get; set; }
        public Nullable<int> Round { get; set; }
        public int Team1 { get; set; }
        public int Team2 { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Teams Teams { get; set; }
        public virtual Teams Teams1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matches> Matches { get; set; }
    }
}
