//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupTables
    {
        public int ID { get; set; }
        public int Team { get; set; }
        public Nullable<long> Poradi { get; set; }
        public int Body { get; set; }
        public int TDfor { get; set; }
        public int TDagainst { get; set; }
        public int Zapasy { get; set; }
        public string Username { get; set; }
        public string Teamname { get; set; }
    }
}
