//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLT.Data
{
    using System;
    
    public enum Inducements : int
    {
        BloodweiserBabes = 1,
        Bribe = 2,
        ExtraReroll = 3,
        HalflingMasterChef = 4,
        Igor = 5,
        WanderingApothecary = 6,
        Wizard = 7,
        StarPlayer = 8,
        Mercenary = 9
    }
}
