//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Action { get; set; }
        public string Message { get; set; }
        public int Author { get; set; }
        public Nullable<int> EntityID { get; set; }
        public string EntityType { get; set; }
    }
}
