//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLT.Data
{
    using System;
    
    public enum LogEvent : int
    {
        Login = 1,
        CompetitionAdd = 2,
        CompetitionEdit = 3,
        CompetitionDelete = 4,
        GroupAdd = 5,
        GroupEdit = 6
    }
}
