//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLT.Data
{
    using System;
    
    public enum MatchEventsTypes : int
    {
        Touchdown = 1,
        Casualty = 2,
        Completion = 3,
        Injury = 4,
        Interception = 5,
        MVP = 6
    }
}
