//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchEvents
    {
        public int ID { get; set; }
        public int Match { get; set; }
        public int EventType { get; set; }
        public int Team { get; set; }
        public int SourcePlayer { get; set; }
        public Nullable<int> TargetPlayer { get; set; }
        public Nullable<int> Result { get; set; }
    
        public virtual Matches Matches { get; set; }
        public virtual Players Players { get; set; }
        public virtual Players Players1 { get; set; }
        public virtual Teams Teams { get; set; }
    }
}
