//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerSkills
    {
        public int ID { get; set; }
        public int Player { get; set; }
        public Skills Skill { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
