//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlayerTypes()
        {
            this.Players = new HashSet<Players>();
            this.TypeGroups = new HashSet<TypeGroups>();
        }
    
        public int ID { get; set; }
        public Races Race { get; set; }
        public string Name { get; set; }
        public Nullable<int> MA { get; set; }
        public Nullable<int> ST { get; set; }
        public Nullable<int> AG { get; set; }
        public Nullable<int> AV { get; set; }
        public Nullable<int> Value { get; set; }
        public string Skillset { get; set; }
        public Nullable<int> Limit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Players> Players { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypeGroups> TypeGroups { get; set; }
    }
}
