//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Players()
        {
            this.MatchEvents = new HashSet<MatchEvents>();
            this.MatchEvents1 = new HashSet<MatchEvents>();
            this.PlayerSkills = new HashSet<PlayerSkills>();
            this.TeamMatchData = new HashSet<TeamMatchData>();
        }
    
        public int ID { get; set; }
        public int Team { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public Nullable<int> MA { get; set; }
        public Nullable<int> ST { get; set; }
        public Nullable<int> AG { get; set; }
        public Nullable<int> AV { get; set; }
        public Nullable<int> SPP { get; set; }
        public Nullable<int> INT { get; set; }
        public Nullable<int> COMP { get; set; }
        public Nullable<int> TD { get; set; }
        public Nullable<int> CAS { get; set; }
        public Nullable<int> Kills { get; set; }
        public Nullable<int> MVP { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<int> NI { get; set; }
        public Nullable<int> MNG { get; set; }
        public Nullable<int> Journeyman { get; set; }
        public Nullable<Status> Status { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> Number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchEvents> MatchEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchEvents> MatchEvents1 { get; set; }
        public virtual PlayerTypes PlayerTypes { get; set; }
        public virtual Teams Teams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerSkills> PlayerSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamMatchData> TeamMatchData { get; set; }
    }
}
