//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLT.Data
{
    using System;
    
    public enum Races : int
    {
        Amazon = 1,
        Chaos = 2,
        ChaosDwarf = 3,
        DarkElf = 4,
        Dwarf = 5,
        Elf = 6,
        Goblin = 7,
        Halfling = 8,
        HighElf = 9,
        Human = 10,
        Khemri = 11,
        Lizardman = 12,
        Necromantic = 13,
        Norse = 14,
        Nurgle = 15,
        Ogre = 16,
        Orc = 17,
        Skaven = 18,
        Undead = 19,
        Vampire = 20,
        WoodElf = 21,
        ChaosPact = 22,
        Slann = 23,
        Underworld = 24,
        Special = 999
    }
}
