//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLT.Data
{
    using System;
    
    public enum Skills : int
    {
        Block = 101,
        Dauntless = 102,
        DirtyPlayer = 103,
        Fend = 104,
        Frenzy = 105,
        Kick = 106,
        KickOffReturn = 107,
        PassBlock = 108,
        Pro = 109,
        Shadowing = 110,
        StripBall = 111,
        SureHands = 112,
        Tackle = 113,
        Wrestle = 114,
        BreakTackle = 201,
        Grab = 202,
        Guard = 203,
        Juggernaut = 204,
        MightyBlow = 205,
        MultipleBlock = 206,
        PilingOn = 207,
        StandFirm = 208,
        StrongArm = 209,
        ThickSkull = 210,
        Catch = 301,
        DivigCatch = 302,
        DivingTackle = 303,
        Dodge = 304,
        JumpUp = 305,
        Leap = 306,
        SideStep = 307,
        SneakyGit = 308,
        Sprint = 309,
        SureFeet = 310,
        Accurate = 401,
        DumpOff = 402,
        HailMaryPass = 403,
        Leader = 404,
        NervesOfSteel = 405,
        Pass = 406,
        SafeThrow = 407,
        BigHand = 501,
        Claw = 502,
        DisturbingPresence = 503,
        ExtraArms = 504,
        FoulAppearance = 505,
        Horns = 506,
        PrehensileTail = 507,
        Tentacles = 508,
        TwoHeads = 509,
        VeryLongLegs = 510,
        AlwaysHungry = 601,
        Animosity = 602,
        BallAndChain = 603,
        BloodLust = 604,
        Bomardier = 605,
        BoneHead = 606,
        Chainsaw = 607,
        Decay = 608,
        FanFavourite = 609,
        HypnoticGaze = 610,
        Loner = 611,
        NoHands = 612,
        NurglesRot = 613,
        ReallyStupid = 614,
        Regeneration = 615,
        RightStuff = 616,
        SecretWeapon = 617,
        Stab = 618,
        Stakes = 619,
        Stunty = 620,
        TakeRoot = 621,
        ThrowTeamMate = 622,
        Titchy = 623,
        WildAnimal = 624
    }
}
