//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLT.Data
{
    using System;
    
    public enum SkillGroups : int
    {
        General = 1,
        Strength = 2,
        Agility = 3,
        Passing = 4,
        Mutation = 5,
        Extraordinary = 6
    }
}
