//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMatchData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeamMatchData()
        {
            this.Matches = new HashSet<Matches>();
            this.Matches1 = new HashSet<Matches>();
            this.TeamInducements = new HashSet<TeamInducements>();
        }
    
        public int ID { get; set; }
        public int Team { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> Gate { get; set; }
        public Nullable<int> Winnings { get; set; }
        public Nullable<int> Fame { get; set; }
        public Nullable<int> FanFactorMod { get; set; }
        public Nullable<int> SpirallingExpense { get; set; }
        public Nullable<int> MVP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matches> Matches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matches> Matches1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamInducements> TeamInducements { get; set; }
        public virtual Teams Teams { get; set; }
        public virtual Players Players { get; set; }
    }
}
