//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teams()
        {
            this.CompTeams = new HashSet<CompTeams>();
            this.Fixtures = new HashSet<Fixtures>();
            this.Fixtures1 = new HashSet<Fixtures>();
            this.MatchEvents = new HashSet<MatchEvents>();
            this.Players = new HashSet<Players>();
            this.TeamMatchData = new HashSet<TeamMatchData>();
        }
    
        public int ID { get; set; }
        public Races Race { get; set; }
        public int Owner { get; set; }
        public string Name { get; set; }
        public int Rerolls { get; set; }
        public Nullable<int> Fanfactor { get; set; }
        public Nullable<int> Asscoaches { get; set; }
        public Nullable<int> Cheerleaders { get; set; }
        public Nullable<int> Apothecary { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<int> Treasury { get; set; }
        public Status Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompTeams> CompTeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixtures> Fixtures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixtures> Fixtures1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchEvents> MatchEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Players> Players { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamMatchData> TeamMatchData { get; set; }
        public virtual Users Users { get; set; }
    }
}
